woozlabs/echo-be

src/main/java/woozlabs/echo/domain/member/entity/Member.java, src/main/java/woozlabs/echo/domain/member/entity/SubAccount.java, src/main/java/woozlabs/echo/domain/member/entity/SuperAccount.java, src/main/java/woozlabs/echo/global/common/entity/BaseEntity.java, src/main/java/woozlabs/echo/global/config/ModuleConfig.java, src/main/java/woozlabs/echo/global/config/RestTemplateConfig.java
- close #11 
- 확장성을 고려하여 생성일, 수정일을 BaseEntity에 담습니다.
- LocalDatetime이 담긴 엔티티를 반환 시 Jackson에서 오류가 발생하여 ObjectMapper 설정을 진행합니다.
- ModuleConfig에 ObjectMapper를 빈으로 등록함에 따라 RestTemplateConfig에서 중복 오류가 발생하여 RestTemplateConfig에서는 제거합니다.
- DB 테이블의 경우 현재 코드를 작성하다가 다시 전부 지운 상태입니다.
- 모델링을 이렇게 한 이유는 처음에는 Sub_Account 테이블만 생성하였는데 첫 로그인이 이루어진 다음에 Member Table에 모두 저장되는 흐름에 따라서 Member Table에서는 모든 계정을 관리, 추후 서브 계정을 추가할 시 Super, Sub Account로 나누는게 어떨까해서 모델링 해놓았습니다.
```java
objectMapper.registerModule(new JavaTimeModule());
```
Object Mapper를 위와 같이 JavaTimeModule을 추가하기 위해서 config로 등록하고 RestTemplate에서 제거해두었는데, 이래도 Gmail이 잘 불러오는지에 대한 확인이 필요합니다.
```text
추가적으로 Gmail 불러오기 과정에서는 헤더에 Bearer token을 실어서 보낼 필요가 없습니다.
-> 구글 측에서 발급한 액세스토큰을 파라미터로 넣고 있기 …
```
=> [Feat] BaseEntity & ObjectMapper 수정, DB 테이블 모델링

src/main/java/woozlabs/echo/domain/member/entity/Member.java, src/main/java/woozlabs/echo/domain/member/entity/SubAccount.java, src/main/java/woozlabs/echo/domain/member/entity/SuperAccount.java, src/main/java/woozlabs/echo/domain/member/repository/SubAccountRepository.java, src/main/java/woozlabs/echo/domain/member/repository/SuperAccountRepository.java, src/main/java/woozlabs/echo/domain/member/service/CustomOAuth2UserService.java, src/main/java/woozlabs/echo/global/security/provider/JwtProvider.java
- close #10 
- [연관관계 맵핑 노션 기록1](https://woozlabs.notion.site/240616-LDH-Multi-Google-Login-9eff688f2fc24f4fa20f67797634fbf4?pvs=4)
- [연관관계 맵핑 노션 기록2](https://woozlabs.notion.site/240616-LDH-Multi-Management-56b6770b0c3541b4be5df6fde6faaca9?pvs=4)
위의 기록을 잘 확인해주시기 바랍니다.
로직이 말로만 보면 상당히 복잡해서 이해하기 힘듭니다.
- 쿠키에 슈퍼 토큰 삽입
- 슈퍼 어카운트 삽입
- 멤버 삽입
- 쿠키에 있는 슈퍼토큰 그대로
-  멤버 삽입
- 서브 어카운트 삽입 (슈퍼 계정을 참조함)
=> [FEAT] Super, Sub Account DB 맵핑

.gitignore, build.gradle, cloudbuild.yml, src/main/java/woozlabs/echo/domain/member/controller/AuthController.java, src/main/java/woozlabs/echo/domain/member/dto/AddAccountRequestDto.java, src/main/java/woozlabs/echo/domain/member/dto/CreateAccountRequestDto.java, src/main/java/woozlabs/echo/domain/member/entity/Member.java, src/main/java/woozlabs/echo/domain/member/entity/SubAccount.java, src/main/java/woozlabs/echo/domain/member/entity/SuperAccount.java, src/main/java/woozlabs/echo/domain/member/repository/SuperAccountRepository.java, src/main/java/woozlabs/echo/domain/member/service/AuthService.java, src/main/java/woozlabs/echo/global/aop/AuthVerifyAspect.java, src/main/java/woozlabs/echo/global/aop/annotations/VerifyToken.java, src/main/java/woozlabs/echo/global/config/FirebaseConfig.java, src/main/java/woozlabs/echo/global/exception/ErrorCode.java, src/main/java/woozlabs/echo/global/utils/FirebaseTokenVerifier.java, src/main/resources/application-prod.yml
- close #24 
- close #25
- add-account 로직을 구현합니다.
- 컨트롤러단에서 Header에 실려온 idToken을 받아서 디코딩합니다.
- 디코딩된 토큰으로 Super 계정의 UID를 얻을 수 있습니다.
모든 컨트롤러단에서 Bearer를 파싱해서 검증해야합니다.
이러한 한 기능의 중복을 제거하기 위해 Spring AOP를 학습 후 적용합니다.
오류가 날 시 cloudbuild.yml을 수정해야합니다.
현재 예상 오류 중 하나는 Firebase 연동으로 serviceAccountKey를 등록해야하는데 원활히 될 지 모르겠습니다.
환경변수로 지정하는 코드를 cloudbuild.yml에 추가해놓았습니다.
아직 테스트는 해보지 못하였습니다.
사용해볼만한 API가 마땅치 않음 -> 테스트 API 생성 필요
클라이언트 코드 부분 수정 안됨
-> 완료
=> [FEAT & REFACTOR] Firebase idToken Verify 로직 구현 & AOP 설정

.dockerignore, .gcloudignore, Dockerfile, cloudbuild.yaml
- close #41 
- 평균적으로 빌드 한번 당 3분 30초가 넘는 시간이 걸려서 확인하는데 많은 시간을 소모하였습니다.
- 빌드 시간을 단축합니다.
- .gcloudignore 파일은 Google Cloud Build에서 파일 업로드를 제어하는 데 사용됩니다.
- .dockerignore 파일은 도커 빌드 컨텍스트에서 불필요한 파일이나 디렉터리를 제외하도록 설정합니다.
=> [CHORE] Build 시간 단축을 위한 세팅

src/main/java/woozlabs/echo/EchoApplication.java, src/main/java/woozlabs/echo/domain/member/entity/Member.java, src/main/java/woozlabs/echo/domain/member/entity/SubAccount.java, src/main/java/woozlabs/echo/domain/member/entity/SuperAccount.java, src/main/java/woozlabs/echo/domain/member/service/TokenSchedulerService.java, src/main/java/woozlabs/echo/global/exception/ErrorCode.java
- close #14 
- RefreshToken을 가져오는 과정을 거쳤으니 이를 사용해서 액세스 토큰을 관리합니다.
- Spring Scheduler를 통해 1분마다 스케줄링을 거칩니다.
- 모든 유저의 액세스 토큰 만료기한을 확인하고 3분 정도가 남았을 경우 새 액세스토큰으로 교체합니다.
[스크린샷 및 짧은 과정 기록](https://ldhbenecia.notion.site/SpringBoot-Scheduler-93ffe9b1e61f4800807a13069b7f6786?pvs=4)
=> [FEAT] Token Scheduler 구현

build.gradle, src/main/java/woozlabs/echo/domain/gmail/controller/GmailController.java, src/main/java/woozlabs/echo/domain/gmail/dto/GmailMessageAttachmentResponse.java, src/main/java/woozlabs/echo/domain/gmail/dto/GmailMessageSendRequest.java, src/main/java/woozlabs/echo/domain/gmail/dto/GmailMessageSendResponse.java, src/main/java/woozlabs/echo/domain/gmail/service/GmailService.java, src/main/java/woozlabs/echo/global/exception/ErrorCode.java
- 이메일 전송 기능 구현 완료
- 이메일 전송 요청은 /api/v1/gmail/messages/send로 요청한다.
- 첨부파일이 있을 수 있으므로 JSON 형태가 아닌 form-data 형태로 요청한다.
- form-data에 포함되어야 할 데이터는 subject, toEmailAddress, bodyText, files(* Optional)이다.
=> [Feat]: 이메일 전송 기능 구현 완료

src/main/java/woozlabs/echo/domain/member/repository/MemberRepository.java, src/main/java/woozlabs/echo/domain/member/service/TokenSchedulerService.java
- close #45 
- 액세스 토큰 재갱신 시 쿼리 최적화를 진행합니다.
- 기존 코드와 멤버의 액세스 토큰 기한 필터링 쿼리를 가지고 성능을 비교합니다.
- 성능 비교 결과 Update를 하는 부분에서 SELECT 쿼리가 예상보다 많이 나가는 점을 발견하여서 페치 조인을 적용했습니다.
스케줄링 | 기존 코드 | 쿼리 최적화 | 쿼리 최적화(페치 조인)
-- | -- | -- | --
1번쨰 | 224ms (조회 7회) | 35ms (조회 1회 - 필터링) | 46ms(조회 1회 - 필터링)
2번쨰 | 114ms (조회 7회) | 31ms (조회 1회 - 필터링) | 37ms(조회 1회 - 필터링)
3번째 + update | 946ms (조회 10회, 업데이트 6회) | 1119ms (조회 10회, 업데이트 6회) | 1071ms(조회 3회, 업데이트 6회
당장 페치조인을 적용한 코드와 안한 코드간의 시간 차이가 크게 없을 수 있으나 장기적으로 데이터가 많이 쌓인다면
조회 쿼리 개수 차이로 인해 얻을 수 있는 이점이 많아보입니다.
아이디어 제공 희관씨 감사링
=> [FEAT] 액세스 토큰 재갱신 시 쿼리 최적화 및 N+1 해결

src/main/java/woozlabs/echo/domain/gmail/controller/GmailController.java, src/main/java/woozlabs/echo/domain/gmail/service/GmailService.java, src/main/java/woozlabs/echo/domain/member/repository/MemberRepository.java, src/main/java/woozlabs/echo/global/config/WebConfig.java, src/main/java/woozlabs/echo/global/constant/GlobalConstant.java, src/main/java/woozlabs/echo/global/interceptor/FirebaseAuthInterceptor.java
1. 제목: [Feat]: Firebase Token 인증을 위한 인터셉터 구현
2. 내용
- 파이어베이스 토큰 검사를 위한 인터셉터 구현
- 클라이언트의 요청으로부터 받은 Authorization 헤더의 값 즉, 파이어베이스 토큰 값을 통해 UID를 추출하고 이를 통해 사용자의 구글 액세스 토큰을 데이터베이스에서 가져오는 코드를 작성하였습니다.
- 인터셉터를 통해 구현하였으며 요청이 핸들러에게 전달되기 전에 검사합니다.
- 현재 /api/v1/gmail/*로 시작하는 경로로 요청이 들어오면 해당 인터셉터가 동작합니다.
=> [Feat]: Firebase Token 인증을 위한 인터셉터 구현

src/main/java/woozlabs/echo/domain/gmail/controller/GmailController.java, src/main/java/woozlabs/echo/domain/gmail/dto/draft/GmailDraftSendRequest.java, src/main/java/woozlabs/echo/domain/gmail/dto/draft/GmailDraftSendResponse.java, src/main/java/woozlabs/echo/domain/gmail/dto/thread/GmailThreadListThreads.java, src/main/java/woozlabs/echo/domain/gmail/dto/thread/GmailThreadUpdateRequest.java, src/main/java/woozlabs/echo/domain/gmail/dto/thread/GmailThreadUpdateResponse.java, src/main/java/woozlabs/echo/domain/gmail/service/AsyncGmailService.java, src/main/java/woozlabs/echo/domain/gmail/service/GmailService.java, src/main/java/woozlabs/echo/domain/gmail/util/GmailUtil.java, src/main/java/woozlabs/echo/global/exception/ErrorCode.java
1. 제목: [Feat] : Draft 전송 기능, 이메일 목록 조회시 내용포함 리팩토링, 이메일 읽음처리 기능
2. 내용: Gmail Draft 전송 기능 구현 완료, 기존의 이메일 목록 조회 기능에서 이메일 내용이 포함되어되도록 변경함. 이메일 읽음처리를 위해 Label을 업데이트 할 수 있도록 기능을 구현하였음
- Draft 전송 기능 구현 완료
- 기존의 이메일 목록 조회 기능에서 이메일 내용이 포함되어되도록 변경
- 이메일 읽음처리를 위해 Label을 업데이트 할 수 있도록 기능을 구현
- 이메일 읽기 전
- 이메일 읽은 후
=> [Feat] : Draft 전송 기능, 이메일 목록 조회시 내용포함 리팩토링, 이메일 읽음처리 기능

src/main/java/woozlabs/echo/domain/gmail/dto/thread/GmailThreadListThreads.java, src/main/java/woozlabs/echo/domain/gmail/service/AsyncGmailService.java
1. 제목: [Fix]: 첨부파일 중복 문제 해결
2. 내용
- 메일 조회시 인라인 파일도 첨부파일로 처리되는 문제가 발생 -> 해결
- 타임존 모두 UTC로 통합
- 메일 조회시 인라인 파일도 첨부파일로 처리되는 문제가 발생 -> 해결
- 메일 내용 내에 인라인으로 이미지 파일을 보내경우 첨부파일로 된 파일이 하나 더 추가가 되는데 이것을 2개의 파일로 인식하는 경우가 발생했음. 이를 해결하기 위해 인라인 파일은 무시하도록 필터링 메서드를 개발함.
- 타임존 모두 UTC로 통합. 이전에는 모든 메일이 타임존이 달랐음.
- 변경전
- 변경후
=> [Fix]: 첨부파일 중복 문제 해결 & 타입존 UTC로 통합

src/main/java/woozlabs/echo/domain/member/service/AuthService.java, src/main/java/woozlabs/echo/domain/member/service/TokenSchedulerService.java, src/main/java/woozlabs/echo/global/constant/GlobalConstant.java
- close #70
- Token 스케줄러에서 예상치 못한 NullPoint Exception 발생
- 정확한 이유는 모르겠으나, DB 확인 결과 멤버와 슈퍼어카운트의 리프레쉬 토큰 값이 다른것을 확인
- SubAccount는 우선 처리하지않습니다.
=> [FEAT] Token Member, SuperAccount 동기화

src/main/java/woozlabs/echo/domain/chatGPT/ChatGPTInterface.java, src/main/java/woozlabs/echo/domain/chatGPT/controller/ChatGptController.java, src/main/java/woozlabs/echo/domain/chatGPT/dto/ChatGPTRequest.java, src/main/java/woozlabs/echo/domain/chatGPT/dto/ChatGPTResponse.java, src/main/java/woozlabs/echo/domain/chatGPT/service/ChatGptService.java, src/main/java/woozlabs/echo/domain/gemini/controller/GeminiController.java, src/main/java/woozlabs/echo/domain/gemini/prompt/VerificationMailPrompt.java, src/main/java/woozlabs/echo/domain/gemini/service/GeminiService.java, src/main/java/woozlabs/echo/domain/member/service/TokenSchedulerService.java, src/main/java/woozlabs/echo/global/config/RestTemplateConfig.java, src/main/java/woozlabs/echo/global/exception/ErrorCode.java
- close #102 
- 이메일 Thread HTML Content를 받아옵니다.
- 해당 컨텐츠를 필요한 태그만 남기고 파싱 처리합니다.
- 파싱하고 남은 값을 가지고 해당 메일이 Verification 메일인지 아닌지를 판별하고, 맞다면 Code or URL을 반환합니다.
- 인증 메일이 아니라면 `false`만 반환합니다.
- 인증 메일일 시 url이 주어진다면 `<url_title=https://link.t~~~`
- Code가 주어진다면 `<code=123456>`
- 결과 캡쳐본들은 슬랙에서 확인
=> [FEAT] Verification gemini & ChatGPT Setting 및 초안 설계 구현

src/main/java/woozlabs/echo/domain/member/service/TokenSchedulerService.java
- 저번 account 수정 이후로 토큰 스케줄러 코드를 수정했었는데 최적화를 좀 더 진행합니다.
- 수정 전 로직은 토큰을 발급 받은 후로부터 50분이 지난 멤버를 리스트로 뽑아냅니다.
- 그리고 해당 멤버들이 50분이 지났는지 또 한번 재검사를 한 후 리프레쉬를 요청합니다.
- 여기서 한번 더 재검사를 하는 로직이 불필요하다고 판단되어 코드를 수정합니다.
=> [REFACTOR] 중복 시간 검사 로직 수정

src/main/java/woozlabs/echo/domain/member/service/AuthService.java, src/main/java/woozlabs/echo/global/exception/ErrorCode.java
- Firebase Custom Claims는 인증된 사용자의 ID 토큰에 사용자 정의 정보를 추가하는 기능을 제공합니다. 
- 이를 통해 사용자 역할, 그룹 정보 등의 커스텀 데이터를 저장하고 클라이언트 애플리케이션에서 이를 활용할 수 있습니다.
- Auth 시 SignIn, addAccount 메서드 때 해당 Firebase Custom Token에 Custom Claims로 해당 계정의 uid 값들의 묶음을 추가합니다.
=> [FEAT] Auth Custom Claims 적용

build.gradle, src/main/java/woozlabs/echo/domain/gmail/dto/thread/GmailThreadGetMessages.java, src/main/java/woozlabs/echo/domain/gmail/service/GmailService.java, src/main/java/woozlabs/echo/domain/gmail/util/GmailUtility.java, src/main/java/woozlabs/echo/global/exception/ErrorCode.java, src/main/resources/keywords_en.txt
1. 제목: [Feat]: 인증 메일 링크 추출 기능 GPT 연동 성공
2. 내용: 인증 메일 링크 추출 기능 구현
- 메일에서 인증 링크를 추출하는 기능을 구현하였습니다. 로직은 다음과 같습니다.
1. 이메일 내용 Base64 디코딩 후 1차 필터링
2. 1차 필터링은 자체적으로 구현한 "keywords_en.txt"과 "keywords_ko.txt"에 작성된 키워드를 확인하며 해당 키워드가 포함된 태그 또는 <a> 태그이면서 내부 텍스트에 키워드를 가지고 있는 경우의 Element를 모두 수집합니다.
3. 필요하지 않은 태그들을 제거합니다. -> Ex. style, script ..
4. <a> 태그를 제외한 내용이 없는 태그를 제거합니다.
5. href 속성을 제외하고 모든 Attribute를 제거합니다.
6. url이 너무 길 수 있으므로 자원을 표시하는 뒷 부분을 제거한 메인 도메인만 남기도록 합니다.
7. 각 태그에 id로 "%04d" 형태의 번호를 부여합니다.
8. GPT 연동을 통해 인증 링크가 존재하는 부분의 id를 반환받습니다. 만약 인증 이메일이 아니라면 false 값을 반환하도록 @ldhbenecia 님이 프롬프팅 코딩을 해주셨습니다.
9. 반환받은 결과값을 가지고 false가 아닌 id 값을 반환받았을 경우 해당 id 태그의 href 링크를 가져와 반환합니다.
- 위의 방법을 적용한 이후 GPT의 Input으로 들어가는 글자수가 약 6000자에서 -> 
- 아직 인증 코드에는 적용되지 않았습니다. 인증 링크 추출 기능에만 적용된 상태입니다.
- 현재 결과값은 제대로 나오지만 속도가 …
=> [Feat]: 인증 메일 링크 추출 기능 GPT 연동 성공

src/main/java/woozlabs/echo/domain/gmail/dto/thread/GmailThreadGetMessages.java, src/main/java/woozlabs/echo/domain/gmail/service/AsyncGmailService.java, src/main/java/woozlabs/echo/domain/gmail/service/GmailService.java, src/main/java/woozlabs/echo/domain/gmail/util/GmailUtility.java, src/main/java/woozlabs/echo/global/constant/GlobalConstant.java
1. 제목: [Fix]: 요일 데이터가 없는 Timezone 버그 해결 & [Refactor]: 비동기 처리 불필요로 인해 동기+멀티쓰레드 방식으로 변경
2. 내용: 요일이 존재하지 않는 Timezone의 버그를 해결하기 위해 날짜 파싱 로직에 정규표현식을 추가함. 비동기 처리가 불필요하기 때문에 동기 처리로 변경하고, 멀티쓰레드 처리를 하였음.
- "Sun, "과 같이 날짜가 존재하지 않는 date를 처리하기 위해 정규표현식을 추가로 작성함.
- 기존에는 비동기 + 병렬 처리를 이용하였음. 그러나 결과적으로 멀티쓰레딩 실행 결과를 기다려야 하므로 불필요한 비동기 처리를 제거하고 동기로 변경하였습니다.
- ExecutorService를 이용하여 멀티 쓰레드 병렬처리를 하도록 하였음. -> 현재 쓰레드 수는 코어수로 처리하였으며 이후에 필요시 해당 쓰레드 수를 적절하게 조절할 필요가 있음.
- 코어 수만큼 쓰레드 풀을 생성하도록 함.
- 적절한 쓰레드 수를 잘 정해야할 것 같습니다. 의견 있으시면 말씀해주세요.
=> [Fix]: 요일 데이터가 없는 Timezone 버그 해결 & [Refactor]: 비동기 처리 불필요로 인해 동기+멀티쓰레드 방식으로 변경

build.gradle, src/main/java/woozlabs/echo/domain/member/entity/Member.java, src/main/java/woozlabs/echo/domain/signature/Signature.java, src/main/java/woozlabs/echo/domain/team/controller/TeamController.java, src/main/java/woozlabs/echo/domain/team/dto/CreateTeamRequestDto.java, src/main/java/woozlabs/echo/domain/team/dto/SendInvitationEmailDto.java, src/main/java/woozlabs/echo/domain/team/dto/TeamInvitationRequestDto.java, src/main/java/woozlabs/echo/domain/team/dto/TeamMemberDto.java, src/main/java/woozlabs/echo/domain/team/dto/TeamResponseDto.java, src/main/java/woozlabs/echo/domain/team/entity/PrivateComment.java, src/main/java/woozlabs/echo/domain/team/entity/Role.java, src/main/java/woozlabs/echo/domain/team/entity/SharedEmail.java, src/main/java/woozlabs/echo/domain/team/entity/Team.java, src/main/java/woozlabs/echo/domain/team/entity/TeamInvitation.java, src/main/java/woozlabs/echo/domain/team/entity/TeamMember.java, src/main/java/woozlabs/echo/domain/team/repository/SharedEmailRepository.java, src/main/java/woozlabs/echo/domain/team/repository/TeamInvitationRepository.java, src/main/java/woozlabs/echo/domain/team/repository/TeamRepository.java, src/main/java/woozlabs/echo/domain/team/service/EmailService.java, src/main/java/woozlabs/echo/domain/team/service/SharedEmailService.java, src/main/java/woozlabs/echo/domain/team/service/TeamService.java, src/main/java/woozlabs/echo/global/config/MongoConfig.java, src/main/java/woozlabs/echo/global/constant/GlobalConstant.java, src/main/java/woozlabs/echo/global/exception/ErrorCode.java, src/main/java/woozlabs/echo/global/scheduler/AccessTokenScheduler.java, src/main/java/woozlabs/echo/global/scheduler/JunkInvitationScheduler.java, src/main/resources/templates/invite-email.html
- close #97
- close #111 
- 외부에서 메일, 비밀번호만으로 요청을 날리는 것이 더이상 지원되지 않게 됨
- 현재 MailSender의 경우 메일과 비밀번호만으로 요청을 날리는 형식이나 위의 방식이 지원되지 않게됨
- 2차 인증을 걸은 다음 16자리의 앱 키를 등록받아서 해당 앱 키를 비밀번호로 사용하면 추출 가능함
- 현재 echo.develop 구글 계정은 2차 인증을 못함 @leokim8012 도움 필요
- 인증 이후 앱 키를 받아서 등록하면 우선적으로 echo 개발 gmail 계정으로 이메일을 날릴 예정
평균 5, 6s -> 100ms
=> [FEAT] Team, Invitation

src/main/java/woozlabs/echo/domain/contactGroup/controller/ContactGroupController.java, src/main/java/woozlabs/echo/domain/echo/controller/EmailTemplateController.java, src/main/java/woozlabs/echo/domain/team/controller/SharedInboxController.java, src/main/java/woozlabs/echo/domain/team/controller/TeamController.java, src/main/java/woozlabs/echo/domain/team/dto/ShareEmailRequestDto.java, src/main/java/woozlabs/echo/domain/team/dto/thread/ThreadGetBody.java, src/main/java/woozlabs/echo/domain/team/dto/thread/ThreadGetMessages.java, src/main/java/woozlabs/echo/domain/team/dto/thread/ThreadGetMessagesBcc.java, src/main/java/woozlabs/echo/domain/team/dto/thread/ThreadGetMessagesCc.java, src/main/java/woozlabs/echo/domain/team/dto/thread/ThreadGetMessagesFrom.java, src/main/java/woozlabs/echo/domain/team/dto/thread/ThreadGetMessagesTo.java, src/main/java/woozlabs/echo/domain/team/dto/thread/ThreadGetPart.java, src/main/java/woozlabs/echo/domain/team/dto/thread/ThreadGetPayload.java, src/main/java/woozlabs/echo/domain/team/dto/thread/ThreadGetResponse.java, src/main/java/woozlabs/echo/domain/team/entity/SharedEmail.java, src/main/java/woozlabs/echo/domain/team/entity/Thread.java, src/main/java/woozlabs/echo/domain/team/repository/SharedInboxRepository.java, src/main/java/woozlabs/echo/domain/team/repository/ThreadRepository.java, src/main/java/woozlabs/echo/domain/team/service/SharedEmailService.java, src/main/java/woozlabs/echo/domain/team/service/SharedInboxService.java
- close #112 
- Shared Email - Private Comments - 설계
- 팀 구성:
- 팀을 만들고 초대 링크를 통해 팀원 초대
- 이메일 공유:
- 팀원이 앱에서 특정 이메일을 보다가 '공유하기' 버튼을 클릭
- 해당 이메일의 정보(스레드 ID, 제목 등)가 `SharedEmail` 테이블(MongoDB 컬렉션)에 저장
- 데이터 저장:
- `SharedEmail` 문서에는 공유된 이메일의 메타데이터(스레드 ID, 제목, 공유한 사람 등)가 저장
- 실제 이메일 내용은 저장하지 않고, 스레드 ID를 이용해 원본 이메일을 참조
- 공유된 이메일 접근:
- 팀원들은 공유된 이메일 목록을 볼 수 있음
- 특정 공유 이메일을 선택하면, 앱은 저장된 스레드 ID를 사용하여 원본 이메일 내용을 가져와 표시
- 프라이빗 코멘트:
- `PrivateComment` 컬렉션을 사용하여 공유된 이메일에 대한 팀 내부 코멘트를 저장
- 각 코멘트는 특정 `SharedEmail`과 연결되어 있음
- 딥링크:
- 각 `SharedEmail`에 대한 고유 URL을 생성하여 팀 내에서 쉽게 공유할 수 있도록
=> [FEAT] SharedEmail Inbox

src/main/java/woozlabs/echo/domain/team/controller/SharedInboxController.java, src/main/java/woozlabs/echo/domain/team/controller/TeamController.java, src/main/java/woozlabs/echo/domain/team/entity/Role.java, src/main/java/woozlabs/echo/domain/team/entity/ShareStatus.java, src/main/java/woozlabs/echo/domain/team/entity/SharedEmail.java, src/main/java/woozlabs/echo/domain/team/repository/SharedInboxRepository.java, src/main/java/woozlabs/echo/domain/team/repository/TeamMemberRepository.java, src/main/java/woozlabs/echo/domain/team/service/SharedInboxService.java, src/main/java/woozlabs/echo/domain/team/service/TeamService.java, src/main/java/woozlabs/echo/domain/team/utils/AuthorizationUtil.java, src/main/java/woozlabs/echo/global/exception/ErrorCode.java
- close #124 
- 메일을 공유하거나 작업할 때 권한에 따라 작업 유무를 분리해야합니다.
- ADMIN: 팀원 추가/제거, 권한 관리, 이메일 삭제 및 발송 가능
- EDITOR: 초안 편집 및 발송, 이메일 삭제 가능
- VIEWER: 이메일 및 초안 조회만 가능
- 외부인을 위한 PUBLIC_VIEWER role도 추가합니다.
1. uid를 통해 해당 멤버를 찾은 후 그 멤버가 해당 Team에 속해있는지 확인합니다.
2. 이후 TeamMember로 해당 멤버를 불러옵니다.
3. TeamMember로 그 멤버의 팀내 역할(권한)을 찾고 해당 공유 메일의 상태와 비교합니다.
4. Util 클래스를 통해 해당 멤버의 권한이 그 기능에 대해 접근할 수 있는지 판별합니다.
=> [FEAT] 팀내 기능에 따른 기능 접근 제어 #1

build.gradle, src/main/java/woozlabs/echo/domain/member/controller/MemberController.java, src/main/java/woozlabs/echo/domain/member/service/MemberService.java, src/main/java/woozlabs/echo/domain/team/dto/TeamInvitationRequestDto.java, src/main/java/woozlabs/echo/global/config/AsyncConfig.java, src/main/java/woozlabs/echo/global/exception/ErrorCode.java, src/main/resources/db/migration/V1__init.sql, src/test/java/woozlabs/echo/domain/team/service/EmailServiceTest.java
- 추후 프로덕션 환경을 위해서 DB 형상 관리를 위한 flyway를 추가합니다.
- flyway에 V1__init을 넣어두고 커밋메세지는 어제 날짜인 240823으로 해두었는데 프로덕션 직전의 엔티티 구조에 맞춰서 설정해둔 후
프로덕션 환경에서는 `ddl-auto`를 `valid`로 설정하면 됩니다.
- SES 검증을 할겸 속도비교를 위해 다시 코드를 확인하고 테스트코드를 작성했는데 예상한 속도와 달라서 테스트코드 재작성이 필요해보입니다.
- 테스트 환경에서 비동기가 어떻게 돌아가는지와 조금의 학습 및 구현이 필요합니다.
- 내일 이사 후 계정 추가에 대해서 설계할 예정입니다.
=> [REFACTOR] AWS SES 속도 검증, 테스트 코드 및 flyway DB Migration 적용 및 잡무

src/main/java/woozlabs/echo/domain/gmail/dto/message/GmailMessageGetResponse.java, src/main/java/woozlabs/echo/domain/gmail/dto/thread/GmailThreadGetMessagesResponse.java, src/main/java/woozlabs/echo/domain/gmail/dto/thread/GmailThreadGetResponse.java, src/main/java/woozlabs/echo/domain/gmail/dto/thread/GmailThreadListThreads.java, src/main/java/woozlabs/echo/domain/gmail/service/GmailService.java, src/main/java/woozlabs/echo/domain/gmail/service/MultiThreadGmailService.java, src/main/java/woozlabs/echo/global/utils/GlobalUtility.java
1. 제목: [Refactor & Fix]: Date 타입 변경 및 Timezone 변환 버그 해결
2. 내용: Date 타입 변경 및 Timezone 변환 버그 해결
- @leokim8012 의 요청사항에 따라 이메일 Date의 타입을 String -> Long 타입으로 변경하였습니다.
- Timezone 변환 문제 해결(?), 기존의 문제점은 CDT, PDT, KST 등의 비표준대 시간을 처리하지 못한다는 문제가 있었다. 앞서 #143  Joda-time 과 같은 라이브러리를 사용해보려 했으나 이것 또한 비표준대 시간대를 완전하게 처리하지 못했다. 따라서 직접 구현하는 방법을 선택했다. 변환 과정은 다음과 같다.
1. 가장 처음에는 "America/New York"과 같은 일반적인 타임존 형태인지 확인후 처리
2. 만약 에러 발생시 -> ZoneId의 축약형 리스트를 보면서 "GMT"와 같이 표준 시간대의 축약형인지 확인 -> ZoneId의 축약형 타임존 리스트에도 비표준 시간대는 포함되어 있지 않음.
3. 이 경우도 에러가 발생한다면 이것은 비표준 시간대이기 때문에 결국엔 전체 모든 시간대를 확인하며 축약형을 찾는다.
=> [Refactor & Fix]: Date 타입 변경 및 Timezone 변환 버그 해결

src/main/java/woozlabs/echo/domain/gmail/controller/PubSubController.java, src/main/java/woozlabs/echo/domain/gmail/service/GmailService.java, src/main/java/woozlabs/echo/domain/gmail/service/PubSubService.java, src/main/java/woozlabs/echo/global/exception/ErrorCode.java, src/main/java/woozlabs/echo/global/utils/GlobalUtility.java
1. 제목: [Feat]: Billing 관련 이메일 필터링 기능 구현
2. 내용: Billing 관련 이메일 필터링 기능 구현. 이후에 도입될 빌링 기능에 대해 결제를 하지 않았을 경우 메일의 일부 데이터만 전달하도록 기능을 구현해야 했다.
- 결제를 하지 않았을 경우
- 사이드 바에 존재하는 쿼리를 날렸을 경우 60일 이전 데이터까지만 전송하도록 "after: 현재 날짜 기준 60일 이전 날짜" 쿼리를 추가하였음.
- 만약 검색을 통해 복합 쿼리를 날렸을 경우 일단 스레드 데이터를 가져온 후 가장 첫 데이터가 60일보다 더 이전의 메일이면 402 상태코드와 함께 에러를 반환하도록 하였음. 
- 결제를 하였을 경우
- 기존과 그대로 데이터 반환
- 빌링 관련 에러 처리
=> [Feat]: Billing 관련 이메일 필터링 기능 구현
