woozlabs/echo-be

build.gradle
src/main/java/woozlabs/echo/domain/member/repository/MemberRepository.java
src/main/java/woozlabs/echo/global/security/SecurityConfig.java
src/main/java/woozlabs/echo/global/security/filter/JwtAuthenticationFilter.java
src/main/java/woozlabs/echo/global/security/handler/OAuth2SuccessHandler.java
src/main/java/woozlabs/echo/global/security/provider/JwtProvider.java
src/main/resources/static/index.html

- Jwt 토큰을 사용하여 생성 후 헤더에 실어서 클라이언트로 보냅니다.
- 클라이언트로부터 요청이 올 경우 해당 토큰이 올바른지 검증하는 필터를 구현합니다.
- Jwt 버전은 0.12.3 최신 버전을 사용하여 사용 시 공식문서가 필요할 수 있습니다. (블로그 내용 대부분이 예전 버전)

[Feat] Google OAuth Success Handler, Filter

---

src/main/java/woozlabs/echo/domain/email/service/AsyncEmailService.java
src/main/java/woozlabs/echo/domain/member/service/CustomOAuth2UserService.java
src/main/java/woozlabs/echo/global/exception/CustomErrorException.java
src/main/java/woozlabs/echo/global/exception/CustomErrorResponse.java
src/main/java/woozlabs/echo/global/exception/CustomExceptionHandler.java
src/main/java/woozlabs/echo/global/exception/ErrorCode.java

- close #8 
<br />
- throw new에 대한 Exception 처리의 틀을 미리 작성합니다.
<br />
- 다음과 같은 형식으로 에러 코드를 미리 작성합니다.
<br />
- 현재 작성되어있는 로직 중에서는 AsyncEmailService의 경우 에러 코드에 대한 로직이 작성되어있어 처리하였습니다.
현재 Gmail을 불러오는 과정을 제가 테스트를 해본적이 없어서 스크린샷을 찍을 수 없습니다.

[Feat] 전역 Exception 처리 구현

---

.gitignore
Dockerfile
build.gradle
src/main/resources/application-prod.yml

[CHORE]: Google CloudRun Docker Setting

---

cloudbuild.yml
src/main/resources/static/index.html

- Issue에 대한 작업을 처리한 경우 PR과 Issue 연결하기
- 왜 이 작업을 했는지 상세하게 작성하기
- PR에 대해 고민한 과정을 함께 작성하기

[CHORE] Google CloudRun CI/CD - cloudbuild.yml

---

src/main/java/woozlabs/echo/domain/calendar/controller/CalendarController.java
src/main/java/woozlabs/echo/domain/calendar/service/CalendarService.java

- close #52 
- Firebase Intercepter Google Calendar 적용

[REFACTOR] Firebase Intercepter Google Calendar 적용

---

src/main/java/woozlabs/echo/domain/gmail/controller/GmailController.java
src/main/java/woozlabs/echo/domain/gmail/service/GmailService.java

1. 제목: [Refactor]: CamelCase 오탈자 및 인터셉터 미적용 부분 수정
2. 내용
- gmail 관련 인터셉터 미적용 부분 수정
- messages 관련 API CamelCase 미적용 부분 수정
- 내용과 동일

[Refactor]: CamelCase 오탈자 및 인터셉터 미적용 부분 수정

---

src/main/java/woozlabs/echo/global/config/WebConfig.java

- close #55 
- WebConfig에서 인터셉터 도메인 적용을 하지않아서 404가 뜨는 오류를 수정합니다.

[FIX] Google Calender 404 오류 수정

---

src/main/java/woozlabs/echo/domain/member/service/TokenSchedulerService.java

[Refactor] 스케줄링 주기 5분으로 변경

---

src/main/java/woozlabs/echo/domain/calendar/controller/CalendarController.java
src/main/java/woozlabs/echo/domain/gemini/GeminiInterface.java
src/main/java/woozlabs/echo/domain/gemini/controller/GeminiController.java
src/main/java/woozlabs/echo/domain/gemini/dto/GeminiRequest.java
src/main/java/woozlabs/echo/domain/gemini/dto/GeminiResponse.java
src/main/java/woozlabs/echo/domain/gemini/service/GeminiService.java
src/main/java/woozlabs/echo/domain/member/controller/AuthController.java
src/main/java/woozlabs/echo/domain/member/service/AuthService.java
src/main/java/woozlabs/echo/domain/member/service/TokenSchedulerService.java
src/main/java/woozlabs/echo/global/config/RestTemplateConfig.java
src/main/java/woozlabs/echo/global/exception/CustomErrorException.java
src/main/java/woozlabs/echo/global/exception/CustomErrorResponse.java
src/main/java/woozlabs/echo/global/exception/CustomExceptionHandler.java
src/test/java/woozlabs/echo/domain/gemini/service/GeminiServiceTest.java

- close #61 
- Gemini API를 사용하기 위한 SpringBoot 세팅
- HttpInterface를 사용한 처리 방식입니다.
- 구글 서칭을 해서 찾은 글 중 하나의 포스트를 따라했습니다.
- 알아보기 힘든 에러코드 때문에 Detail message를 추가했습니다.
- 이 메세지는 서버 자체에서 발행하는 e.getmessage()입니다.
[Gemini HttpInterface Setting 정리](https://ldhbenecia.notion.site/HttpInterface-eb525b28e3a64e86945b79edc8d9f894?pvs=4)

[FEAT] Gemini API Setting & Error Code 

---

src/main/java/woozlabs/echo/domain/gmail/controller/GmailController.java
src/main/java/woozlabs/echo/domain/gmail/service/GmailService.java
src/main/java/woozlabs/echo/global/exception/ErrorCode.java

1. 제목: 메일 관련 에러 메세지 세분화
2. 내용: 에러 세분화
- Gmail 관련 에러 세분화

[Fix]: 에러 코드 수정

---

build.gradle
src/main/java/woozlabs/echo/domain/gemini/controller/GeminiController.java
src/main/java/woozlabs/echo/domain/gemini/prompt/ThreadSummaryPrompt.java
src/main/java/woozlabs/echo/domain/gemini/service/GeminiService.java
src/main/java/woozlabs/echo/global/config/WebConfig.java
src/main/java/woozlabs/echo/global/exception/ErrorCode.java
src/test/java/woozlabs/echo/domain/gemini/service/GeminiServiceTest.java

- close #62 
1. 목표를 명확히 설정한다.
2. 명료하고 간결하게 작성하여 혼동을 방지한다.
3. 필요한 만큼의 세부정보를 제공하여 기대에 부합하는 콘텐츠를 생성한다.
4. 사람과 대화할때 사용하는 자연어를 사용하여 AI의 이해를 쉽게 돕는다.
5. 맥락이나 배경정보를 제공하여 이해를 돕는다.
6. 개방형 질문은 창의적인 응답, 폐쇄형 질문은 단조로운 응답을 들을 수 있기에 조절한다.
7. 시행착오를 겪으며 개선한다.
```
You are an AI assistant specializing in creating extremely concise email summaries.
Your task is to provide a brief summary of the given Gmail thread, focusing on the most important points.
Guidelines:
1. Summarize in just 1 sentence with no more than 10 words.
2. Focus on the most critical information, action items, or decisions.
3. Omit all pleasantries, greetings, signatures, and unnecessary details.
4. Present the summary as a single, cohesive sentence.
5. Do not mention names or email addresses unless absolutely crucial to the context.
6. Use …
```

[FEAT] Gmail Snippet Summarize with GEMINI

---

src/main/java/woozlabs/echo/domain/gemini/controller/GeminiController.java
src/main/java/woozlabs/echo/domain/gemini/dto/ChangeToneRequest.java
src/main/java/woozlabs/echo/domain/gemini/prompt/ThreadKeypointPrompt.java
src/main/java/woozlabs/echo/domain/gemini/prompt/ThreadSummaryPrompt.java
src/main/java/woozlabs/echo/domain/gemini/service/GeminiService.java
src/main/java/woozlabs/echo/domain/member/controller/MemberController.java
src/main/java/woozlabs/echo/global/exception/ErrorCode.java

- close #67 
- 구문 형태로 나올떄도 있고 안나올 때도 있음
- 언어 감지가 자주 틀림
- 현재 프롬포트는 언어감지는 잘 되나 구문 형태가 간혹 틀리는 경우가 있음

[FEAT] GEMINI AI Writer

---

src/main/java/woozlabs/echo/domain/gmail/controller/GmailController.java
src/main/java/woozlabs/echo/domain/gmail/dto/draft/GmailDraftUpdateResponse.java
src/main/java/woozlabs/echo/domain/gmail/dto/thread/GmailThreadGetMessages.java
src/main/java/woozlabs/echo/domain/gmail/dto/thread/GmailThreadListThreads.java
src/main/java/woozlabs/echo/domain/gmail/service/AsyncGmailService.java
src/main/java/woozlabs/echo/domain/gmail/service/GmailService.java
src/main/java/woozlabs/echo/global/config/WebConfig.java
src/main/java/woozlabs/echo/global/constant/GlobalConstant.java
src/main/java/woozlabs/echo/global/exception/ErrorCode.java

1. 제목: [Feat] : BCC, CC 기능 추가 & 타임존 문제 해결
2. 내용: 메일에서 참조(CC), 숨은참조(BCC)를 확인할 수 있는 기능을 추가하였습니다. 그리고 메일 조회시 타임존 조회 가능하도록 하였습니다.
- 기존에 메일 조회시 BCC, CC가 조회되지 않았습니다. 해당 부분의 기능을 추가하였습니다.
- 쓰레드의 각 메세지 조회시 타임존 또한 반환하도록 하였습니다. ZoneId가 아닌 ZoneName을 반환하도록 하였습니다.
- 타임존 필드 반환 예시 & BCC, CC 조회 기능 구현

[Feat] : BCC, CC 기능 추가 & 타임존 문제 해결

---

src/main/java/woozlabs/echo/domain/gmail/controller/GmailController.java
src/main/java/woozlabs/echo/domain/gmail/controller/PubSubController.java
src/main/java/woozlabs/echo/domain/gmail/dto/pubsub/FcmTokenRequest.java
src/main/java/woozlabs/echo/domain/gmail/dto/pubsub/FcmTokenResponse.java
src/main/java/woozlabs/echo/domain/gmail/dto/thread/GmailThreadListThreads.java
src/main/java/woozlabs/echo/domain/gmail/service/AsyncGmailService.java
src/main/java/woozlabs/echo/domain/gmail/service/GmailService.java
src/main/java/woozlabs/echo/domain/gmail/service/PubSubService.java
src/main/java/woozlabs/echo/domain/member/entity/FcmToken.java
src/main/java/woozlabs/echo/domain/member/repository/FcmTokenRepository.java
src/main/java/woozlabs/echo/global/config/WebConfig.java
src/main/java/woozlabs/echo/global/constant/GlobalConstant.java

1. 제목: [Fix]: Timezone 버그 해결 & [Feat]: FcmToken 저장 API 구현
2. 내용: Timezone 버그 해결 및 FCMToken 관련 API 구현 완료
- Timezone 기능을 개발하면서 정규표현식이 맞지 않는 경우가 존재하여 에러가 발생하였음. 좀 더 범용적인 정규표현식 사용을 통해 에러 해결
- FCMToken을 DB에 저장할 수 있도록 Member 테이블에 FcmToken 컬럼을 추가함. -> 타입 String
- /api/v1/fcm을 통해 POST 요청을 보낼 경우 FCM 토큰을 저장하도록 함.
- FcmToken : Member = N : 1

[Fix]: Timezone 버그 해결 & [Feat]: FcmToken 저장 API 구현

---

src/main/java/woozlabs/echo/domain/echo/controller/EmailTemplateController.java
src/main/java/woozlabs/echo/domain/echo/dto/emailTemplate/CreateEmailTemplateRequest.java
src/main/java/woozlabs/echo/domain/echo/dto/emailTemplate/EmailTemplateResponse.java
src/main/java/woozlabs/echo/domain/echo/dto/emailTemplate/UpdateEmailTemplateRequest.java
src/main/java/woozlabs/echo/domain/echo/entity/EmailRecipient.java
src/main/java/woozlabs/echo/domain/echo/entity/EmailTemplate.java
src/main/java/woozlabs/echo/domain/echo/repository/EmailTemplateRepository.java
src/main/java/woozlabs/echo/domain/echo/service/EmailTemplateService.java
src/main/java/woozlabs/echo/domain/gemini/prompt/ThreadSummaryPrompt.java
src/main/java/woozlabs/echo/domain/member/entity/Member.java
src/main/java/woozlabs/echo/global/config/WebConfig.java
src/main/java/woozlabs/echo/global/exception/ErrorCode.java
src/test/java/woozlabs/echo/domain/echo/service/EmailTemplateServiceTest.java

- close #72 
- close #74 
- email template을 서버에서 관리합니다.
- to 기능에 대해서 이 템플릿을 사용할 대상자를 지정한다고 이해하였습니다. -> 배열로 나와있기 때문
- 그래서 이메일 템플릿에서 해당 템플릿을 사용할 대상자를 지정하는 EmailRecipients 테이블을 하나 더 생성하였습니다.
- EmailTemplate <-> EmailRecipients 1:N의 구조를 띄고 있습니다.
- 밑의 이미지를 확인할 시 to에 지정할 사용자의 메일을 넣을 시 DB에 기록합니다.
- 밑의 양식 구조에서 body는 백틱으로 지정되고 있으나 String 형태로 입력받아야합니다.
```javascript
const defaultTemplates = atom<TemplateAtom[]>([
{
key: 0,
templateName: ‘Request’,
subject: ‘’,
to: [],
body: `Dear Mr./Ms. [Last name],<br><br>
I would like to request a vacation from Monday, September 9th till Friday, September 13th.<br><br>
I will make sure to complete all my current projects and pending tasks in advance before the vacation. My colleagues [Name] and [Name] will cover my responsibilities during my absence.<br><br> …
```

[FEAT] Email Template & Thread Summarize Prompt

---

src/main/java/woozlabs/echo/domain/echo/controller/EmailTemplateController.java
src/main/java/woozlabs/echo/domain/echo/dto/emailTemplate/CreateEmailTemplateRequest.java
src/main/java/woozlabs/echo/domain/echo/dto/emailTemplate/EmailTemplateResponse.java
src/main/java/woozlabs/echo/domain/echo/dto/emailTemplate/UpdateEmailTemplateRequest.java
src/main/java/woozlabs/echo/domain/echo/entity/EmailRecipient.java
src/main/java/woozlabs/echo/domain/echo/entity/EmailTemplate.java
src/main/java/woozlabs/echo/domain/echo/repository/EmailTemplateRepository.java
src/main/java/woozlabs/echo/domain/echo/service/EmailTemplateService.java
src/main/java/woozlabs/echo/domain/gemini/prompt/ThreadSummaryPrompt.java
src/main/java/woozlabs/echo/domain/member/controller/MemberController.java
src/main/java/woozlabs/echo/domain/member/dto/ProfileResponseDto.java
src/main/java/woozlabs/echo/domain/member/entity/Member.java
src/main/java/woozlabs/echo/domain/member/repository/MemberRepository.java
src/main/java/woozlabs/echo/domain/member/service/MemberService.java
src/main/java/woozlabs/echo/global/config/WebConfig.java
src/main/java/woozlabs/echo/global/exception/ErrorCode.java
src/test/java/woozlabs/echo/domain/echo/service/EmailTemplateServiceTest.java

- close #82 
- `/api/v1/member/profile?email=`

[FEAT] User Profile

---

src/main/java/woozlabs/echo/domain/member/service/TokenSchedulerService.java
src/main/java/woozlabs/echo/global/exception/ErrorCode.java
src/main/java/woozlabs/echo/global/utils/GoogleOAuthUtils.java

- Token 스케줄러에서 오류가 발생하여 확인을 위한 로그를 작성합니다.

[FEAT] Token Error Logging

---

src/main/java/woozlabs/echo/domain/member/service/TokenSchedulerService.java

Refactor: 토큰 재갱신 주기 변경

---

src/main/java/woozlabs/echo/domain/member/service/TokenSchedulerService.java

- 토큰 재 갱신 시 모든 테이블에 대해서 수정해줬으나 같은 리프레쉬 토큰을 공유하기 때문에 멤버를 변경 후 동기화 시킵니다.

[REFACTOR] Token 갱신 로직 변경

---

src/main/java/woozlabs/echo/domain/member/service/AuthService.java

- Claims Key 명칭 superAccountUids -> accounts

[STYLE] Claims Key 명칭 superAccountUids -> accounts

---

build.gradle
src/main/java/woozlabs/echo/domain/team/service/EmailService.java
src/main/java/woozlabs/echo/domain/team/service/TeamService.java
src/main/java/woozlabs/echo/global/config/AwsSesConfig.java

[FEAT] Aws SES

---

src/main/java/woozlabs/echo/domain/gemini/controller/GeminiController.java
src/main/java/woozlabs/echo/domain/gemini/dto/ChangeToneRequest.java
src/main/java/woozlabs/echo/domain/gemini/dto/GeminiRequest.java
src/main/java/woozlabs/echo/domain/gemini/prompt/ThreadSummaryPrompt.java
src/main/java/woozlabs/echo/domain/gemini/service/GeminiService.java

- close #120 
- Thread Summary 부분에서 영어로된 Input Text로 요청을 보냈지만 스페인어로 응답이 오는 현상을 수정합니다.
- 문구 Tone을 바꾸는 ChangeTone 기능에 대해서 특정 부분만 변경할 수 있도록 구조를 수정합니다.
- 구조를 수정하기 위해 GeminiRequest 부분에 contents, parts로 받는 생성자를 추가하였으며, 응답문도 추가하였습니다.

[FEAT] Thread Summary Prompt & Change Tone

---

src/main/java/woozlabs/echo/domain/team/dto/SendInvitationEmailDto.java
src/main/java/woozlabs/echo/domain/team/service/EmailService.java
src/main/java/woozlabs/echo/domain/team/service/TeamService.java
src/main/resources/templates/invite-email.html

-  Invitation 수정 - ip, location 제거 및 Invitee Role 추가

[FEAT] Invitation 수정 - ip, location 제거 및 Invitee Role 추가

---

src/main/java/woozlabs/echo/global/config/WebConfig.java
src/main/java/woozlabs/echo/global/constant/GlobalConstant.java
src/main/java/woozlabs/echo/global/interceptor/FirebaseAuthInterceptor.java

Fix: History 목록 조회 & pub/sub 알림 기능 버그 수정

Fix: History 목록 조회 & pub/sub 알림 기능 버그 수정

---

src/main/java/woozlabs/echo/domain/gemini/controller/GeminiController.java
src/main/java/woozlabs/echo/domain/gemini/dto/ProofreadResponse.java
src/main/java/woozlabs/echo/domain/gemini/prompt/ProofreadPrompt.java
src/main/java/woozlabs/echo/domain/gemini/service/GeminiService.java
src/main/java/woozlabs/echo/global/exception/ErrorCode.java

- close #130 
간혹 추가 개행 문자 같은게 껴서 오류가 날 때도 있습니다.
이때는 오류를 반환하고 있습니다.
UI/UX적으로 처리를 할 때 오류가 발생하면 오류를 뱉는것 보다는 변경 도중에 애니메이션을 무한으로 걸어주면, 
사용자 입장에서 왜 안되지 한번 더 요청하지 않을까 생각이 들었습니다.

[FEAT] GEMINI Proofread 추가 사항 구현

---

src/main/java/woozlabs/echo/domain/gmail/dto/thread/GmailThreadGetResponse.java
src/main/java/woozlabs/echo/domain/gmail/dto/thread/GmailThreadListThreads.java
src/main/java/woozlabs/echo/domain/gmail/service/GmailService.java
src/main/java/woozlabs/echo/domain/gmail/service/MultiThreadGmailService.java

Refactor: getThread 데이터 구조 변경

---

build.gradle

[CHORE] flyway 프로덕션 전까지 사용 해제

---

src/main/java/woozlabs/echo/domain/gmail/controller/GmailController.java
src/main/java/woozlabs/echo/domain/gmail/controller/PubSubController.java
src/main/java/woozlabs/echo/domain/gmail/dto/message/GmailMessageGetResponse.java
src/main/java/woozlabs/echo/domain/gmail/dto/thread/GmailThreadGetMessagesResponse.java
src/main/java/woozlabs/echo/domain/gmail/dto/thread/GmailThreadListThreads.java
src/main/java/woozlabs/echo/domain/gmail/entity/VerificationEmail.java
src/main/java/woozlabs/echo/domain/gmail/repository/VerificationEmailRepository.java
src/main/java/woozlabs/echo/domain/gmail/service/GmailService.java
src/main/java/woozlabs/echo/domain/gmail/service/PubSubService.java
src/main/java/woozlabs/echo/domain/gmail/util/GmailUtility.java
src/main/java/woozlabs/echo/global/constant/GlobalConstant.java
src/main/java/woozlabs/echo/global/interceptor/FirebaseAuthInterceptor.java

1. 제목: [Refactor]: timezone 문제 해결
2. 내용: 타임존 버그 해결 시도
- 기존에 이메일 헤더의 Date 필드를 가져와 날짜를 처리하였음. 하지만 포맷이 너무 일관되지 않아 이메일 조회시 버그가 많이 발생하였음
- 이를 해결하기 위해 Date 헤더가 아닌 타임존이 UTC로 통일된 internalDate 필드를 이용하여 리팩토링 하였음.

[Refactor]: timezone 문제 해결

---

src/main/java/woozlabs/echo/domain/gmail/service/PubSubService.java

1. 제목: [Fix]: Forwarding 이메일 알림 2개 보내지는 버그 해결
2. 내용: 이메일 포워딩시 알림 2개 가는 버그가 존재했었음.
- 이메일 포워딩 시 알림 2개가 가는 버그가 존재했었음.
- 이것의 원인은 아래의 첫번째 스크린샷과 같이 포워딩 메세지를 처리하기 때문임.
- 따라서 Cloud pub/sub으로부터 알림이 왔을 때 메세지가 3개이고, message_added, message_deleted, message_added 순으로 메세지 타입이 이루어졌을 경우 포워딩 된 것으로 판단함.

[Fix]: Forwarding 이메일 알림 2개 보내지는 버그 해결

---

src/main/java/woozlabs/echo/domain/gmail/entity/VerificationEmail.java
src/main/java/woozlabs/echo/domain/gmail/service/PubSubService.java
src/main/java/woozlabs/echo/domain/member/repository/AccountRepository.java
src/main/java/woozlabs/echo/global/scheduler/AccessTokenScheduler.java

- 충돌 수정이 잘못되어 빌드 오류가 발생해서 수정합니다.
- 토큰 스케줄러에서의 메서드명칭을 변경합니다.

[REFACTOR/FIX] PubSubService Conflict 수정 및 스케줄러 메서드 명칭 변경

---

build.gradle
src/main/java/woozlabs/echo/domain/gmail/dto/message/GmailMessageGetResponse.java
src/main/java/woozlabs/echo/domain/gmail/dto/thread/GmailThreadGetMessagesResponse.java
src/main/java/woozlabs/echo/domain/gmail/service/PubSubService.java
src/main/java/woozlabs/echo/domain/member/utils/AuthCookieUtils.java
src/main/java/woozlabs/echo/global/constant/GlobalConstant.java
src/main/java/woozlabs/echo/global/utils/GlobalUtility.java

1. 제목: [Refactor]: timezone 해결 & from 데이터 처리
2. 내용: 타임존 문제 해결 및 from 데이터 처리
- Timestamp를 변환하지 않고 반환하도록 변경
- 타임존 또한 변환하지 않고 그대로 추출하여 반환하도록 변경
- From 데이터의 경우 이름이 존재하지 않고 메일만 존재할 경우 "@" 앞까지만 추출하여 반환하도록 함

[Refactor]: timezone 해결 & from 데이터 처리

---

src/main/java/woozlabs/echo/domain/gmail/dto/message/GmailMessageGetResponse.java

Refactor: message 조회 from 데이터 설정 방식 변경

Refactor: message 조회 from 데이터 설정 방식 변경

---

src/main/java/woozlabs/echo/domain/gmail/dto/message/GmailMessageGetResponse.java
src/main/java/woozlabs/echo/domain/gmail/dto/thread/GmailThreadGetMessagesResponse.java
src/main/java/woozlabs/echo/domain/gmail/service/GmailService.java

Fix: Timezone 필드 제거

---

cloudbuild.yaml

Style: cloudbuild.yaml 파일 수정

---

build.gradle
src/main/java/woozlabs/echo/EchoApplication.java
src/main/java/woozlabs/echo/domain/gmail/dto/message/GmailMessageGetResponse.java
src/main/java/woozlabs/echo/domain/gmail/dto/thread/GmailThreadGetMessagesResponse.java
src/main/java/woozlabs/echo/global/utils/GlobalUtility.java

Fix: 빌드 에러 수정 시도

---

cloudbuild.yaml
src/main/java/woozlabs/echo/domain/member/controller/AccountController.java
src/main/java/woozlabs/echo/domain/member/dto/AccountProfileResponseDto.java
src/main/java/woozlabs/echo/domain/member/dto/NotificationDto.java
src/main/java/woozlabs/echo/domain/member/dto/PreferenceDto.java
src/main/java/woozlabs/echo/domain/member/service/AccountService.java
src/main/java/woozlabs/echo/domain/member/service/MemberService.java

- Issue에 대한 작업을 처리한 경우 PR과 Issue 연결하기
- 왜 이 작업을 했는지 상세하게 작성하기
- PR에 대해 고민한 과정을 함께 작성하기

[CHORE, FEAT] GcloudBuild 캐싱 제거 및 로그 추가 및 Preference 업데이트 단일 가능 처리

---

cloudbuild.yaml

[FIX] cloudbuild.yml 오탈자

---

src/main/java/woozlabs/echo/domain/member/entity/Theme.java

- Theme 입력 시 ENUM 타입으 대문자가 아닌 소문자로 받기 위한 작업을 합니다.

[REFACTOR] Theme 역직렬화 

---

src/main/java/woozlabs/echo/domain/gmail/controller/GmailController.java
src/main/java/woozlabs/echo/domain/gmail/dto/draft/GmailDraftGetMessage.java
src/main/java/woozlabs/echo/domain/gmail/dto/message/GmailMessageGetResponse.java
src/main/java/woozlabs/echo/domain/gmail/dto/thread/GmailThreadGetMessagesResponse.java
src/main/java/woozlabs/echo/domain/gmail/dto/thread/GmailThreadGetResponse.java
src/main/java/woozlabs/echo/domain/gmail/dto/thread/GmailThreadListThreads.java
src/main/java/woozlabs/echo/domain/gmail/service/GmailService.java
src/main/java/woozlabs/echo/domain/gmail/service/MultiThreadGmailService.java
src/main/java/woozlabs/echo/domain/sharedEmail/dto/thread/ThreadGetMessages.java

Refactor: Date 필드명 Timestamp로 변경

Refactor: Date 필드명 Timestamp로 변경

---

src/main/java/woozlabs/echo/domain/gmail/dto/draft/GmailDraftGetMessage.java
src/main/java/woozlabs/echo/domain/gmail/dto/message/GmailMessageGetResponse.java
src/main/java/woozlabs/echo/domain/gmail/dto/thread/GmailThreadGetMessagesResponse.java
src/main/java/woozlabs/echo/domain/gmail/service/GmailService.java
src/main/java/woozlabs/echo/domain/gmail/service/MultiThreadGmailService.java
src/main/java/woozlabs/echo/global/constant/GlobalConstant.java

Style: Uppercase로 변경

---

src/main/java/woozlabs/echo/domain/gmail/service/GmailService.java

Style: 로깅 코드 추가

---

src/main/java/woozlabs/echo/domain/gmail/service/GmailService.java

Refactor: Billing 관련 코드 pagetoken이 없을 때는 그대로 반환 하도록 변경

Refactor: Billing 관련 코드 pagetoken이 없을 때는 그대로 반환 하도록 변경

---

src/main/java/woozlabs/echo/domain/member/controller/MemberController.java
src/main/java/woozlabs/echo/domain/team/entity/Role.java
src/main/java/woozlabs/echo/global/scheduler/AccessTokenScheduler.java
src/main/java/woozlabs/echo/global/utils/GoogleOAuthUtils.java

- UpdatePreference 메서드는 업데이트 로직으로 HTTP 메서드를 PATCH로 변경합니다.
- 왜 이 작업을 했는지 상세하게 작성하기
- PR에 대해 고민한 과정을 함께 작성하기

[REFACTOR] 잡무 및 스케줄러 수정

---

src/main/java/woozlabs/echo/domain/member/dto/AppearanceDto.java
src/main/java/woozlabs/echo/domain/member/entity/Member.java
src/main/java/woozlabs/echo/domain/member/service/MemberService.java

- Preference 작업 중 Density를 추가합니다.

[FEAT] Density 생성 처리

---

src/main/java/woozlabs/echo/domain/gemini/dto/ProofreadResponse.java
src/main/java/woozlabs/echo/domain/gemini/prompt/ProofreadPrompt.java
src/main/java/woozlabs/echo/domain/member/service/MemberService.java

- GEMINI Proofread type을 추가합니다.

[FEAT] GEMINI Proofread type, getPreference

---

src/main/java/woozlabs/echo/domain/member/dto/AppearanceDto.java
src/main/java/woozlabs/echo/domain/member/entity/Density.java
src/main/java/woozlabs/echo/domain/member/entity/Member.java
src/main/java/woozlabs/echo/domain/member/service/MemberService.java

- Density를 0, 1 int value에서 Enum String으로 변경합니다.

[REFACTOR] Density Enum String 변경

---

src/main/java/woozlabs/echo/domain/team/utils/AuthorizationUtil.java

- SharedEmail 구체화 및 수정으로 인해 전에 작성한 Util 파일을 임의로 주석 처리합니다.

[TEMP] AuthorizationUtil 파일 임의로 주석 처리
